### ISSUE TITLE
Return type of frame velocities

### ISSUE THREAD

**Issue by ezavod** [chemfiles/chemfiles.rs#25]
Should `frame.velocities()` return an Option?

This would eliminate the use of boilerplate code like
```rust
let velocities = if frame.has_velocities() {
    Some(frame.velocities())
} else {
    None
};
```
(from #24) and would make the Rust API more similar to the C++ API which uses `optional<span<Vector3D>>`.

**Comment by Luthaf** [comment]
I though it already did to be honest =) So go for it if you have the time!

**Comment by ezavod** [comment]
I'll try to remember fixing it before the next release.
For now, I'll leave it open as it's a "good first issue". If anyone needs help, feel free to ping me.
