### ISSUE TITLE
Implement Debug for Trajectory

### ISSUE THREAD

**Issue by schneiderfelipe** [chemfiles/chemfiles.rs#30]
It looks like that `Trajectory` does not implement `Debug`

https://github.com/chemfiles/chemfiles.rs/blob/9f3b1b289605984dc7815341b6b7324b49533e02/src/trajectory.rs#L14-L19

Is there a reason for that?

**Comment by ezavod** [comment]
AFAIK there is no reason for that. It would be really useful to be able to debug print all the different structs in chemfiles, not only `Trajectory`.
The Python bindings already implement a string representation (e.g. [`Trajectory`](https://github.com/chemfiles/chemfiles.py/blob/4d2a2b16ec2d68172f6359630c1de60fbc0787bc/src/chemfiles/trajectory.py#L146-L147) and [`Atom`](https://github.com/chemfiles/chemfiles.py/blob/4d2a2b16ec2d68172f6359630c1de60fbc0787bc/src/chemfiles/atom.py#L37-L41)) which might be useful as a template for what to print with `fmt()`.

**Comment by schneiderfelipe** [comment]
The simplest implementation possible would be to derive `Debug` for both `CHFL_TRAJECTORY` and `Trajectory`.
I'm sure the second can be done in a single line (`#[derive(Debug)]`), not certain about the first one though, as it is defined in the glue between C and Rust, and I'm not familiarized with the details on that.

I'm slightly against matching what is done in the Python case, as that would incur an overhead most people wouldn't like to have in their Rust code.

**Just to clarify my use case**:

```rust
#[derive(Debug)]
struct NamedTrajectory {
    name: String,
    trajectory: chemfiles::Trajectory,
}

let name = "some name".into();
let trajectory = get_trajectory_somewhere();
let output = format!("{:?}", NamedTrajectory { name, trajectory });
assert_eq!(output, r#"NamedTrajectory { name: "some name", trajectory: Trajectory }"#);
```

I would like the code above to compile. It's OK for me if `chemfiles::Trajectory` is an opaque type, as shown in the expected output above.

**Comment by Luthaf** [comment]
Adding a basic `#[derive(Debug)]` on all structs would be fine with me. It would not be very informative (just print the address of the underlying pointer), but would make it easier to integrate chemfiles in other software.
