### ISSUE TITLE
Decouple argument types in Trajectory::memory_reader

### ISSUE THREAD

**Issue by schneiderfelipe** [chemfiles/chemfiles.rs#31]
This is sort of a suggestion, but the current signature is

https://github.com/chemfiles/chemfiles.rs/blob/9f3b1b289605984dc7815341b6b7324b49533e02/src/trajectory.rs#L140-L141

when it could be

```rust
pub fn memory_reader<'a, S, T>(data: S, format: T) -> Result<Trajectory, Error> 
where S: Into<&'a str>,
      T: Into<&'a str>,
...
```

which would allow things such as

```rust
let data = if maybe_should_modify_string {
    maybe_modifies_string("cc")  // may sometimes allocate, so returns Cow<'_, str>
} else {
    "cc".into()
};
let _ = Trajectory::memory_reader(data, "SMI")?;
...
```

As a side note, is there a reason why it is `Into<&'a str>` and not `AsRef<str>`?

**Comment by Luthaf** [comment]
Putting the format as a different type sounds like a good idea!

> As a side note, is there a reason why it is Into<&'a str> and not AsRef<str>?

Now that you ask, I realise that this function should be marked as unsafe/use a different type than Trajectory as it's output. The C++ code is borrowing `data` (hence the `Into<&'a str>` to be able to track the lifetime), but this is not reflected in the Rust type system. I think we can do something like 

```rs
struct MemoryTrajectoryReader<'a> {
    inner: Trajectory,
    marker: std::marker::PhantomData<'a ()>,
}

impl<'a> Deref for MemoryTrajectoryReader<'a> {
    type Target = &'a Trajectory;

   // ...
}
```

**Comment by Luthaf** [comment]
right, the `type Target` should be `Trajectory;` (without the reference), and the resulting `&Trajectory` would not be allowed to outlive `'a`
