### ISSUE TITLE
Shouldn't guess_format accept &Path instead of &str?

### ISSUE THREAD

**Issue by schneiderfelipe** [chemfiles/chemfiles.rs#32]
In

https://github.com/chemfiles/chemfiles.rs/blob/9f3b1b289605984dc7815341b6b7324b49533e02/src/misc.rs#L127-L136

one would expect `&Path` ([even better: `AsRef<Path>`](https://stackoverflow.com/q/66026309/4039050)) to be received instead of `&str`, as [the conversion from the first to the second may fail in Rust due to Unicode requirements](https://doc.rust-lang.org/std/path/struct.Path.html#method.to_str).

Maybe there's a reason for that?

**Comment by Luthaf** [comment]
No reason, I'm happy to change this, especially given that the Trajectory takes `AsRef<Path>` already.

I'm on holidays until the end of the month, so I will not be able to make these changes or review PR myself until then.
