### ISSUE TITLE
Error handling in guess_format

### ISSUE THREAD

**Issue by schneiderfelipe** [chemfiles/chemfiles.rs#33]
`chemfiles::guess_format` checks errors by using `check_success`, which panics, but it could use `check` and return an error without panicking. Maybe there's a reason for that?

https://github.com/chemfiles/chemfiles.rs/blob/9f3b1b289605984dc7815341b6b7324b49533e02/src/misc.rs#L127-L136

A suggested modification would be

```rust
        // From line 131:
        check(chfl_guess_format( 
            path.as_ptr(), buffer.as_mut_ptr(), buffer.len() as u64 
        ))?;
```

and changing the return type accordingly.

For reference:

https://github.com/chemfiles/chemfiles.rs/blob/92e393bfa3ba53b7dc0d02d151e843e3baa3bdc5/src/errors.rs#L108-L120

**Comment by Luthaf** [comment]
That sounds like something I overlooked, changing the return type to handles errors would be better.
